version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=fridayfinance
      - POSTGRES_USER=user_friday
      - POSTGRES_PASSWORD=p4ssw0rd
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5432:5432'
volumes:
  postgres: